---
language: node_js
node_js:
  - 11
script:
  # use latest npm to work on node9
  - npm install -g npm
  # install required global npm packages
  - npm install -g codecov
  - npm install -g @microsoft/rush
  # testing
  - rush update --full
  - rush rebuild
  - rush test
after_success:
  # code coverage & codecov upload
  - rm -Rf .nyc_output && mkdir -p .nyc_output
  - find packages/**/.nyc_output -type f -name '*.json' -exec cp '{}' .nyc_output \;
  - npx nyc report --reporter=text-lcov > .nyc_output/coverage.lcov
  - codecov
