export enum XcertAbilities {
  MANAGE_ABILITIES = 1,
  ALLOW_MANAGE_ABILITIES = 2,
  CREATE_ASSET = 16,
  REVOKE_ASSET = 32,
  TOGGLE_TRANSFERS = 64,
  UPDATE_ASSET_IMPRINT = 128,
  UPDATE_URI_BASE = 256,
  ALLOW_CREATE_ASSET = 512,
  ALLOW_UPDATE_ASSET_IMPRINT = 1024,
}
