export enum XcertAbilities {
  MANAGE_ABILITIES = 1,
  CREATE_ASSET = 2,
  REVOKE_ASSET = 4,
  TOGGLE_TRANSFERS = 8,
  UPDATE_ASSET_IMPRINT = 16,
  ALLOW_CREATE_ASSET = 32,
  UPDATE_URI_BASE = 64,
  ALLOW_UPDATE_ASSET_IMPRINT = 128,
}
